export const signup = async (req, res) => {
  try {
  } catch (error) {
    console.log("error in signup controller", error);
  }
};

export const login = async (req, res) => {
  try {
  } catch (error) {
    console.log("error in login controller", error);
  }
};

export const logout = async (req, res) => {
  try {
  } catch (error) {
    console.log("error in logout controller", error);
  }
};
